// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM1CokqXC-wnUyjmbDfhSjOPhH67TeuIQ',
    appId: '1:423372761341:web:16294edc7f789710d73694',
    messagingSenderId: '423372761341',
    projectId: 'campusconnect-week8-9',
    authDomain: 'campusconnect-week8-9.firebaseapp.com',
    storageBucket: 'campusconnect-week8-9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Oij7CtS6J_1MReVn_YUBWOmXu1CjfHM',
    appId: '1:423372761341:android:d7075b4d3921d2a6d73694',
    messagingSenderId: '423372761341',
    projectId: 'campusconnect-week8-9',
    storageBucket: 'campusconnect-week8-9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3gg7EbOQ1iBkr5bJxmHSwdazwvkPQWws',
    appId: '1:423372761341:ios:521fcbc6d82841dcd73694',
    messagingSenderId: '423372761341',
    projectId: 'campusconnect-week8-9',
    storageBucket: 'campusconnect-week8-9.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3gg7EbOQ1iBkr5bJxmHSwdazwvkPQWws',
    appId: '1:423372761341:ios:521fcbc6d82841dcd73694',
    messagingSenderId: '423372761341',
    projectId: 'campusconnect-week8-9',
    storageBucket: 'campusconnect-week8-9.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM1CokqXC-wnUyjmbDfhSjOPhH67TeuIQ',
    appId: '1:423372761341:web:90a1d733fb12f36ed73694',
    messagingSenderId: '423372761341',
    projectId: 'campusconnect-week8-9',
    authDomain: 'campusconnect-week8-9.firebaseapp.com',
    storageBucket: 'campusconnect-week8-9.firebasestorage.app',
  );

}