// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnbGZ7Q_92YvTJD1rFqyoVhMonFd6rXlk',
    appId: '1:553895735128:web:a36460a401463d8a20bf2d',
    messagingSenderId: '553895735128',
    projectId: 'authenticated-user-dashb-d771e',
    authDomain: 'authenticated-user-dashb-d771e.firebaseapp.com',
    storageBucket: 'authenticated-user-dashb-d771e.firebasestorage.app',
    measurementId: 'G-K8CC162DRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3HO2oOhlCxiFbeefDzpQrff0tUGHUGTo',
    appId: '1:553895735128:android:aa839cd5f196b6f820bf2d',
    messagingSenderId: '553895735128',
    projectId: 'authenticated-user-dashb-d771e',
    storageBucket: 'authenticated-user-dashb-d771e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbmUK4Do2VMch4-cM-jJXP3zTIOMBFlkw',
    appId: '1:553895735128:ios:1230dafb860d674020bf2d',
    messagingSenderId: '553895735128',
    projectId: 'authenticated-user-dashb-d771e',
    storageBucket: 'authenticated-user-dashb-d771e.firebasestorage.app',
    iosClientId: '553895735128-qqtsga6qair2rpr1gjv7c1q69uf24o40.apps.googleusercontent.com',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbmUK4Do2VMch4-cM-jJXP3zTIOMBFlkw',
    appId: '1:553895735128:ios:1230dafb860d674020bf2d',
    messagingSenderId: '553895735128',
    projectId: 'authenticated-user-dashb-d771e',
    storageBucket: 'authenticated-user-dashb-d771e.firebasestorage.app',
    iosClientId: '553895735128-qqtsga6qair2rpr1gjv7c1q69uf24o40.apps.googleusercontent.com',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnbGZ7Q_92YvTJD1rFqyoVhMonFd6rXlk',
    appId: '1:553895735128:web:74f3f28e23e69b3020bf2d',
    messagingSenderId: '553895735128',
    projectId: 'authenticated-user-dashb-d771e',
    authDomain: 'authenticated-user-dashb-d771e.firebaseapp.com',
    storageBucket: 'authenticated-user-dashb-d771e.firebasestorage.app',
    measurementId: 'G-T32KXYQFKX',
  );
}
